flatpak_remote_install: []

flatpak_package_install:
  - name: app.drey.EarTag
  - name: com.discordapp.Discord
  - name: com.spotify.Client
  - name: com.teamspeak.TeamSpeak3
  - name: org.telegram.desktop

workstation_settings:
  install_fusion_repos: false
  apps: []
