- name: "Create Directories for Nerd Fonts in '~/.local/share/fonts'"
  ansible.builtin.file:
    dest: "{{ ansible_env.HOME }}/.local/share/fonts/{{ item }}"
    state: directory
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
  loop: "{{ global_nerd_fonts + (nerd_fonts | default([])) }}"

- name: "Download Nerd Fonts"
  ansible.builtin.unarchive:
    remote_src: yes
    src: "https://github.com/ryanoasis/nerd-fonts/releases/download/{{ global_nerd_fonts_version }}/{{ item }}.zip"
    dest: "{{ ansible_env.HOME }}/.local/share/fonts/{{ item }}"
  loop: "{{ global_nerd_fonts + (nerd_fonts | default([])) }}"

- name: "Create Directories for Fonts in '~/.local/share/fonts'"
  ansible.builtin.file:
    dest: "{{ ansible_env.HOME }}/.local/share/fonts/{{ item.directory }}"
    state: directory
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
  loop: "{{ global_fonts | default([]) }}"

- name: "Download Fonts"
  get_url:
    url: "{{ item.1 | regex_replace('https://github.com/([^/]+)/([^/]+)/blob/(.+)', 'https://raw.githubusercontent.com/\\1/\\2/\\3') }}"
    dest: "{{ ansible_env.HOME }}/.local/share/fonts/{{ item.0.directory }}/{{ item.1 | urlsplit('path') | basename }}"
    mode: '0644'
  loop: "{{ global_fonts | subelements('urls') }}"
  loop_control:
    label: "{{ item.0.directory }}/{{ item.1 | urlsplit('path') | basename }}"

- name: "Update Fonts Cache"
  ansible.builtin.command:
    cmd: fc-cache -f "{{ ansible_env.HOME }}/.local/share/fonts"
