# Workstation defaults #
########################
workstation_settings: {}
dnf_config: /etc/dnf/dnf.conf

# Flatpaks #
############
global_flatpak_remote_install:
  - name: flathub
    method: user
    state: present
    url: 'https://dl.flathub.org/repo/flathub.flatpakrepo'
  - name: flathub
    method: system
    state: absent
  - name: fedora
    method: system
    state: absent
  - name: fedora
    method: user
    state: absent

global_flatpak_package_install:
  - name: com.github.tchx84.Flatseal
  - name: io.mpv.Mpv
  - name: org.gnome.Calculator
  - name: org.gnome.Characters
  - name: org.gnome.Loupe
  - name: org.gnome.Papers
  - name: org.gnome.Snapshot
  - name: org.gnome.TextEditor
  - name: org.gnome.Weather
  - name: org.mozilla.firefox

# Fonts #
#########
# https://github.com/ryanoasis/nerd-fonts
global_nerd_fonts_version: 'v3.4.0'
global_nerd_fonts:
  - CascadiaCode
  - UbuntuSans
  - JetBrainsMono

# https://github.com/google/fonts
global_fonts:
  - directory: 'Noto Sans'
    urls:
      - "https://github.com/google/fonts/blob/main/ofl/notosans/NotoSans-Italic[wdth,wght].ttf"
      - "https://github.com/google/fonts/blob/main/ofl/notosans/NotoSans[wdth,wght].ttf"
  - directory: 'Ubuntu Sans'
    urls:
      - "https://github.com/google/fonts/blob/main/ufl/ubuntusans/UbuntuSans-Italic[wdth,wght].ttf"
      - "https://github.com/google/fonts/blob/main/ufl/ubuntusans/UbuntuSans[wdth,wght].ttf"
  - directory: 'Inter'
    urls:
      - "https://github.com/google/fonts/blob/main/ofl/inter/Inter-Italic[opsz,wght].ttf"
      - "https://github.com/google/fonts/blob/main/ofl/inter/Inter[opsz,wght].ttf"

# GNOME Settings #
##################
global_dconf_settings:
  - {key: '/org/gtk/gtk4/settings/file-chooser/sort-directories-first', value: 'true'}
  - {key: '/org/gtk/gtk4/Settings/FileChooser/clock-format', value: "'12h'"}
  - {key: '/org/gtk/Settings/FileChooser/clock-format', value: "'12h'",}

# Workstation #
################
global_workstation_settings:
  install_docker: true
  install_fusion_repos: false
  repos:
    absent:
      - /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:peterwu:rendezvous.repo
      - /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:phracek:PyCharm.repo
      - /etc/yum.repos.d/fedora-cisco-openh264.repo
      - /etc/yum.repos.d/fedora-updates-testing.repo
      - /etc/yum.repos.d/google-chrome-canary.repo
      - /etc/yum.repos.d/google-chrome.repo
      - /etc/yum.repos.d/rpmfusion-nonfree-nvidia-driver.repo
  apps:
    - {state: absent, name: 'eog'}
    - {state: absent, name: 'evince'}
    - {state: absent, name: 'gedit'}
    - {state: absent, name: 'gnome-backgrounds'}
    - {state: absent, name: 'gnome-backgrounds-extras'}
    - {state: absent, name: 'gnome-boxes'}
    - {state: absent, name: 'gnome-calculator'}
    - {state: absent, name: 'gnome-characters'}
    - {state: absent, name: 'gnome-contacts'}
    - {state: absent, name: 'gnome-help'}
    - {state: absent, name: 'gnome-maps'}
    - {state: absent, name: 'gnome-photos'}
    - {state: absent, name: 'gnome-software-fedora-langpacks'}
    - {state: absent, name: 'gnome-text-editor'}
    - {state: absent, name: 'gnome-tour'}
    - {state: absent, name: 'loupe'}
    - {state: absent, name: 'malcontent-control'}
    - {state: absent, name: 'nheko'}
    - {state: absent, name: 'rhythmbox'}
    - {state: absent, name: 'showtime'}
    - {state: absent, name: 'totem'}
    - {state: absent, name: 'vlc'}
    - {state: present, name: '1password'}
    - {state: present, name: 'xdg-desktop-portal-gnome'}
    - {state: present, name: 'xdg-desktop-portal-gtk',}

# JetBrains Toolbox #
#####################
install_jetbrains_toolbox: true
