#!/usr/bin/env just --justfile

@_default:
    just --list

# Install dependencies
init:
    sudo dnf install ansible git python3-pip
    ansible-galaxy collection install community.general

configure:
    ansible-playbook -i localhost, 00-silverblue.yml --connection=local
