- name: "Install Utilities"
  hosts: localhost

  tasks:
    - name: "Install 'texlive'"
      become: yes
      dnf:
        state: present
        name:
          - texlive
          - texlive-flowfram
          - texlive-xcharter
          - texlive-cyrillic
          - texlive-collection-fontsextra
          - texlive-microtype
          - texlive-babel-german
          - texlive-collection-latexextra

    - name: "Install 'android-tools'"
      become: yes
      dnf:
        state: present
        name:
          - android-tools
