- name: "Evaluate Playbook config for 1password"
  set_fact:
    install_1password: >-
      {{ global_workstation_settings | is_app_present(workstation_settings, '1password') }}

- name: Add 1password repo using yum_repository
  ansible.builtin.yum_repository:
    name: 1password
    description: 1Password Stable Channel
    baseurl: https://downloads.1password.com/linux/rpm/stable/$basearch
    enabled: yes
    gpgcheck: yes
    repo_gpgcheck: yes
    gpgkey: https://downloads.1password.com/linux/keys/1password.asc
    state: "{{ 'present' if install_1password else 'absent' }}"

- name: Add 1password key
  ansible.builtin.rpm_key:
    state: "{{ 'present' if install_1password else 'absent' }}"
    key: https://downloads.1password.com/linux/keys/1password.asc

- name: Install 1password
  dnf:
    state: "{{ 'present' if install_1password else 'absent' }}"
    name:
      - 1password
