- name: Remove Distribution Docker Packages
  dnf:
    state: absent
    name:
      - docker
      - docker-client
      - docker-client-latest
      - docker-common
      - docker-latest
      - docker-latest-logrotate
      - docker-logrotate
      - docker-engine-selinux
      - docker-engine

- name: Configure Docker DNF Repository
  ansible.builtin.yum_repository:
    name: docker-ce-stable
    description: Docker CE Stable - $basearch
    baseurl: https://download.docker.com/linux/fedora/$releasever/$basearch/stable
    enabled: yes
    gpgcheck: yes
    gpgkey: https://download.docker.com/linux/fedora/gpg
    state: present

- name: Install Official Docker Packages
  dnf:
    state: present
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin

- name: Start Docker
  ansible.builtin.systemd:
    state: started
    name: docker

- name: Fix 'docker.sock' File Permissions
  ansible.builtin.file:
    path: /var/run/docker.sock
    mode: '0666'

- name: Run 'docker ps -a'
  shell: docker ps -a
