- name: "Evaluate Configuration"
  set_fact:
    install_docker: >-
      {{ global_workstation_settings | resolve_setting(workstation_settings, 'install_docker', false) }}
    install_fusion_repos: >-
      {{ global_workstation_settings | resolve_setting(workstation_settings, 'install_fusion_repos', false) }}

- name: "Remove dnf Repositories"
  become: yes
  file:
    path: '{{ item }}'
    state: absent
  loop: "{{ global_workstation_settings | merge_lists(workstation_settings, 'repos.absent') }}"

- name: "Enable RPM Fusion"
  become: true
  when: install_fusion_repos
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  loop:
    - "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"
    - "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm"

- name: "Configure dnf defaultyes"
  become: yes
  ansible.builtin.lineinfile:
    path: '{{ dnf_config }}'
    regexp: 'defaultyes='
    line: defaultyes=True

- name: "Configure dnf max_parallel_downloads"
  become: yes
  ansible.builtin.lineinfile:
    path: '{{ dnf_config }}'
    regexp: 'max_parallel_downloads='
    line: max_parallel_downloads=20

- name: "Configure deltarpm"
  become: yes
  ansible.builtin.lineinfile:
    path: '{{ dnf_config }}'
    regexp: 'deltarpm='
    line: deltarpm=False

- name: Install 1Password
  block:
    - name: "Install 1Password"
      include_tasks: 1password_setup.yml
  become: true

- name: "Configure Native Apps"
  become: true
  dnf:
    state: "{{ item.state }}"
    name: "{{ item.name }}"
  loop: "{{ global_workstation_settings | merge_dict_lists_by_key(workstation_settings, 'apps', 'name') }}"

- name: "Install Docker CE"
  block:
    - name: "Install Docker CE"
      include_tasks: docker_setup.yml
  become: true
  when: install_docker
