- name: "Configure Linux Distribution"
  hosts: localhost

  vars:
    dnf_config: '/etc/dnf/dnf.conf'

  tasks:
    - name: "Install 'dnf-plugins-core'"
      become: yes
      dnf:
        state: present
        name:
          - dnf-plugins-core

    - name: "Remove 'google-chrome' Repo"
      become: yes
      ansible.builtin.file:
        path: /etc/yum.repos.d/google-chrome.repo
        state: absent

    - name: "Remove 'phracek-PyCharm' Repo"
      become: yes
      ansible.builtin.file:
        path: /etc/yum.repos.d/phracek-PyCharm.repo
        state: absent

    - name: "Remove Flatpak Remote 'flathub' - system"
      community.general.flatpak_remote:
        name: flathub
        state: absent
        method: system

    - name: "Remove Flatpak Remote 'fedora'"
      community.general.flatpak_remote:
        name: fedora
        state: absent
        method: user

    - name: "Add RPM Fusion Repos"
      args:
        executable: /bin/bash
      become: yes
      shell: |
        dnf install -y https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm

    - name: "Add Flatpak Remote 'flathub'"
      community.general.flatpak_remote:
        name: flathub
        state: present
        method: user
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

    - name: "Set dnf defaultyes to True"
      become: yes
      ansible.builtin.lineinfile:
        path: '{{ dnf_config }}'
        regexp: 'defaultyes='
        line: defaultyes=True

    - name: "Set dnf max_parallel_downloads to 10"
      become: yes
      ansible.builtin.lineinfile:
        path: '{{ dnf_config }}'
        regexp: 'max_parallel_downloads='
        line: max_parallel_downloads=20

    - name: "Set deltarpm to False"
      become: yes
      ansible.builtin.lineinfile:
        path: '{{ dnf_config }}'
        regexp: 'deltarpm='
        line: deltarpm=False

    - name: "Enable dnf-makecache.timer"
      ansible.builtin.systemd:
        name: dnf-makecache.timer
        enabled: true
        state: started
