- name: "Install & configure Docker"
  hosts: localhost

  tasks:
    - name: "Remove current docker installations"
      become: yes
      dnf:
        state: absent
        name:
          - docker
          - docker-client
          - docker-client-latest
          - docker-common
          - docker-latest
          - docker-latest-logrotate
          - docker-logrotate
          - docker-selinux
          - docker-engine-selinux
          - docker-engine

    - name: "Add docker-ce repository"
      become: true
      shell: |
        dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo

    - name: "Install 'docker-ce'"
      become: yes
      dnf:
        state: present
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io

    - name: "Start docker"
      become: yes
      ansible.builtin.systemd:
        state: started
        name: docker

    - name: "Fix 'docker.sock' file permissions"
      become: yes
      ansible.builtin.file:
        path: /var/run/docker.sock
        mode: '666'

    - name: "Run 'docker ps -a'"
      become: true
      shell: |
        docker ps -a

    - name: "Install 'docker-compose'"
      become: yes
      dnf:
        state: present
        name:
          - docker-compose
